# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.seats_add_body import SeatsAddBody  # noqa: E501
from swagger_client.rest import ApiException


class TestSeatsAddBody(unittest.TestCase):
    """SeatsAddBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeatsAddBody(self):
        """Test SeatsAddBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.seats_add_body.SeatsAddBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
