# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.receipt_api import ReceiptApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReceiptApi(unittest.TestCase):
    """ReceiptApi unit test stubs"""

    def setUp(self):
        self.api = ReceiptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_receipt(self):
        """Test case for download_receipt

        Download Receipt  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
