# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invoices_api import InvoicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self):
        self.api = InvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_charge_invoice(self):
        """Test case for charge_invoice

        Charge Invoice  # noqa: E501
        """
        pass

    def test_download_invoice(self):
        """Test case for download_invoice

        Download Invoice  # noqa: E501
        """
        pass

    def test_get_invoices_for_customer(self):
        """Test case for get_invoices_for_customer

        List Customer Invoices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
