# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.usage_api import UsageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsageApi(unittest.TestCase):
    """UsageApi unit test stubs"""

    def setUp(self):
        self.api = UsageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer_usage_limit(self):
        """Test case for create_customer_usage_limit

        Create Usage Limit  # noqa: E501
        """
        pass

    def test_create_event(self):
        """Test case for create_event

        Create Event  # noqa: E501
        """
        pass

    def test_customer_customer_id_uasge_limit_limit_id_delete(self):
        """Test case for customer_customer_id_uasge_limit_limit_id_delete

        Delete Usage Limit  # noqa: E501
        """
        pass

    def test_get_customer_costs(self):
        """Test case for get_customer_costs

        Usage Cost Estimate  # noqa: E501
        """
        pass

    def test_get_customer_usage_limits_by_id(self):
        """Test case for get_customer_usage_limits_by_id

        Fetch Customer Usage Limits  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
