# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.prices_api import PricesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self):
        self.api = PricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_price(self):
        """Test case for create_price

        Create  # noqa: E501
        """
        pass

    def test_list_price(self):
        """Test case for list_price

        List  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
