# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.checkout_api import CheckoutApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCheckoutApi(unittest.TestCase):
    """CheckoutApi unit test stubs"""

    def setUp(self):
        self.api = CheckoutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_checkout(self):
        """Test case for create_checkout

        Create Checkout  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
