# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.refunds_api import RefundsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRefundsApi(unittest.TestCase):
    """RefundsApi unit test stubs"""

    def setUp(self):
        self.api = RefundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_refunds_for_customer(self):
        """Test case for get_refunds_for_customer

        List Customer Refunds  # noqa: E501
        """
        pass

    def test_list_refund(self):
        """Test case for list_refund

        List  # noqa: E501
        """
        pass

    def test_show_refund_by_id(self):
        """Test case for show_refund_by_id

        Detail  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
