# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.payment_details_api import PaymentDetailsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentDetailsApi(unittest.TestCase):
    """PaymentDetailsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentDetailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_complete_frontend_payment_details(self):
        """Test case for complete_frontend_payment_details

        Complete Frontend Detail Collection  # noqa: E501
        """
        pass

    def test_delete_payment_details(self):
        """Test case for delete_payment_details

        Delete  # noqa: E501
        """
        pass

    def test_delete_payment_details_customer(self):
        """Test case for delete_payment_details_customer

        Delete With Customer  # noqa: E501
        """
        pass

    def test_get_payment_details(self):
        """Test case for get_payment_details

        Fetch  # noqa: E501
        """
        pass

    def test_list_payment_details(self):
        """Test case for list_payment_details

        List Customer's Payment Details  # noqa: E501
        """
        pass

    def test_make_default_payment_details(self):
        """Test case for make_default_payment_details

        Make Default  # noqa: E501
        """
        pass

    def test_make_default_payment_details_customer(self):
        """Test case for make_default_payment_details_customer

        Make Default With Customer  # noqa: E501
        """
        pass

    def test_start_frontend_payment_details(self):
        """Test case for start_frontend_payment_details

        Start Frontend Detail Collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
