# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subscriptions_api import SubscriptionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_seats_subscriptions(self):
        """Test case for add_seats_subscriptions

        Add Seats  # noqa: E501
        """
        pass

    def test_cancel_subscription(self):
        """Test case for cancel_subscription

        Cancel Subscription  # noqa: E501
        """
        pass

    def test_change_subscription_price(self):
        """Test case for change_subscription_price

        Change Price  # noqa: E501
        """
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        Create Subscription  # noqa: E501
        """
        pass

    def test_customer_change_subscription_plan(self):
        """Test case for customer_change_subscription_plan

        Change Subscription Plan  # noqa: E501
        """
        pass

    def test_extend_trial(self):
        """Test case for extend_trial

        Extend Trial Subscription  # noqa: E501
        """
        pass

    def test_get_active_for_customer(self):
        """Test case for get_active_for_customer

        List Customer Active Subscriptions  # noqa: E501
        """
        pass

    def test_get_for_customer(self):
        """Test case for get_for_customer

        List Customer Subscriptions  # noqa: E501
        """
        pass

    def test_list_subscription_plans(self):
        """Test case for list_subscription_plans

        List Subscription Plans  # noqa: E501
        """
        pass

    def test_list_subscriptions(self):
        """Test case for list_subscriptions

        List  # noqa: E501
        """
        pass

    def test_remove_seats_subscriptions(self):
        """Test case for remove_seats_subscriptions

        Remove Seats  # noqa: E501
        """
        pass

    def test_show_subscription_by_id(self):
        """Test case for show_subscription_by_id

        Detail  # noqa: E501
        """
        pass

    def test_start_trial(self):
        """Test case for start_trial

        Start Trial Subscription For Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
