# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customers_api import CustomersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_seats_subscriptions(self):
        """Test case for add_seats_subscriptions

        Add Seats  # noqa: E501
        """
        pass

    def test_apply_voucher_to_customer(self):
        """Test case for apply_voucher_to_customer

        Apply voucher  # noqa: E501
        """
        pass

    def test_create_customer(self):
        """Test case for create_customer

        Create  # noqa: E501
        """
        pass

    def test_create_customer_usage_limit(self):
        """Test case for create_customer_usage_limit

        Create Usage Limit  # noqa: E501
        """
        pass

    def test_customer_customer_id_uasge_limit_limit_id_delete(self):
        """Test case for customer_customer_id_uasge_limit_limit_id_delete

        Delete Usage Limit  # noqa: E501
        """
        pass

    def test_disable_customer(self):
        """Test case for disable_customer

        Disable Customer  # noqa: E501
        """
        pass

    def test_enable_customer(self):
        """Test case for enable_customer

        Enable Customer  # noqa: E501
        """
        pass

    def test_get_active_for_customer(self):
        """Test case for get_active_for_customer

        List Customer Active Subscriptions  # noqa: E501
        """
        pass

    def test_get_all_customers(self):
        """Test case for get_all_customers

        List  # noqa: E501
        """
        pass

    def test_get_customer_by_id(self):
        """Test case for get_customer_by_id

        Detail  # noqa: E501
        """
        pass

    def test_get_customer_costs(self):
        """Test case for get_customer_costs

        Usage Cost Estimate  # noqa: E501
        """
        pass

    def test_get_customer_limits_by_id(self):
        """Test case for get_customer_limits_by_id

        Fetch Customer Limits  # noqa: E501
        """
        pass

    def test_get_customer_usage_limits_by_id(self):
        """Test case for get_customer_usage_limits_by_id

        Fetch Customer Usage Limits  # noqa: E501
        """
        pass

    def test_get_for_customer(self):
        """Test case for get_for_customer

        List Customer Subscriptions  # noqa: E501
        """
        pass

    def test_get_invoices_for_customer(self):
        """Test case for get_invoices_for_customer

        List Customer Invoices  # noqa: E501
        """
        pass

    def test_get_payments_for_customer(self):
        """Test case for get_payments_for_customer

        List Customer Payments  # noqa: E501
        """
        pass

    def test_get_refunds_for_customer(self):
        """Test case for get_refunds_for_customer

        List Customer Refunds  # noqa: E501
        """
        pass

    def test_list_payment_details(self):
        """Test case for list_payment_details

        List Customer's Payment Details  # noqa: E501
        """
        pass

    def test_remove_seats_subscriptions(self):
        """Test case for remove_seats_subscriptions

        Remove Seats  # noqa: E501
        """
        pass

    def test_update_customer(self):
        """Test case for update_customer

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
