# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20014(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'paid': 'bool',
        'failure_reason': 'str'
    }

    attribute_map = {
        'paid': 'paid',
        'failure_reason': 'failure_reason'
    }

    def __init__(self, paid=None, failure_reason=None):  # noqa: E501
        """InlineResponse20014 - a model defined in Swagger"""  # noqa: E501
        self._paid = None
        self._failure_reason = None
        self.discriminator = None
        if paid is not None:
            self.paid = paid
        if failure_reason is not None:
            self.failure_reason = failure_reason

    @property
    def paid(self):
        """Gets the paid of this InlineResponse20014.  # noqa: E501


        :return: The paid of this InlineResponse20014.  # noqa: E501
        :rtype: bool
        """
        return self._paid

    @paid.setter
    def paid(self, paid):
        """Sets the paid of this InlineResponse20014.


        :param paid: The paid of this InlineResponse20014.  # noqa: E501
        :type: bool
        """

        self._paid = paid

    @property
    def failure_reason(self):
        """Gets the failure_reason of this InlineResponse20014.  # noqa: E501


        :return: The failure_reason of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason):
        """Sets the failure_reason of this InlineResponse20014.


        :param failure_reason: The failure_reason of this InlineResponse20014.  # noqa: E501
        :type: str
        """
        allowed_values = ["expired_card", "invalid_details", "fraud", "authentication_required", "invalid_card", "general_decline", "contact_provider", "lack_of_funds"]  # noqa: E501
        if failure_reason not in allowed_values:
            raise ValueError(
                "Invalid value for `failure_reason` ({0}), must be one of {1}"  # noqa: E501
                .format(failure_reason, allowed_values)
            )

        self._failure_reason = failure_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20014, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20014):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
