# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IssueRefundPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'int',
        'currency': 'str',
        'reason': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'currency': 'currency',
        'reason': 'reason'
    }

    def __init__(self, amount=None, currency=None, reason=None):  # noqa: E501
        """IssueRefundPayment - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._currency = None
        self._reason = None
        self.discriminator = None
        self.amount = amount
        if currency is not None:
            self.currency = currency
        if reason is not None:
            self.reason = reason

    @property
    def amount(self):
        """Gets the amount of this IssueRefundPayment.  # noqa: E501


        :return: The amount of this IssueRefundPayment.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this IssueRefundPayment.


        :param amount: The amount of this IssueRefundPayment.  # noqa: E501
        :type: int
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def currency(self):
        """Gets the currency of this IssueRefundPayment.  # noqa: E501

        Three-letter ISO currency code. Must be upper-case  # noqa: E501

        :return: The currency of this IssueRefundPayment.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this IssueRefundPayment.

        Three-letter ISO currency code. Must be upper-case  # noqa: E501

        :param currency: The currency of this IssueRefundPayment.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def reason(self):
        """Gets the reason of this IssueRefundPayment.  # noqa: E501


        :return: The reason of this IssueRefundPayment.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this IssueRefundPayment.


        :param reason: The reason of this IssueRefundPayment.  # noqa: E501
        :type: str
        """

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IssueRefundPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueRefundPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
