# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubscriptionStartBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subscription_plan': 'str',
        'payment_details': 'str',
        'card_token': 'str',
        'price': 'str',
        'schedule': 'str',
        'currency': 'str',
        'seat_numbrers': 'int',
        'deny_trial': 'Bool',
        'metadata': 'object'
    }

    attribute_map = {
        'subscription_plan': 'subscription_plan',
        'payment_details': 'payment_details',
        'card_token': 'card_token',
        'price': 'price',
        'schedule': 'schedule',
        'currency': 'currency',
        'seat_numbrers': 'seat_numbrers',
        'deny_trial': 'deny_trial',
        'metadata': 'metadata'
    }

    def __init__(self, subscription_plan=None, payment_details=None, card_token=None, price=None, schedule=None, currency=None, seat_numbrers=None, deny_trial=None, metadata=None):  # noqa: E501
        """SubscriptionStartBody - a model defined in Swagger"""  # noqa: E501
        self._subscription_plan = None
        self._payment_details = None
        self._card_token = None
        self._price = None
        self._schedule = None
        self._currency = None
        self._seat_numbrers = None
        self._deny_trial = None
        self._metadata = None
        self.discriminator = None
        self.subscription_plan = subscription_plan
        if payment_details is not None:
            self.payment_details = payment_details
        if card_token is not None:
            self.card_token = card_token
        if price is not None:
            self.price = price
        if schedule is not None:
            self.schedule = schedule
        if currency is not None:
            self.currency = currency
        if seat_numbrers is not None:
            self.seat_numbrers = seat_numbrers
        if deny_trial is not None:
            self.deny_trial = deny_trial
        if metadata is not None:
            self.metadata = metadata

    @property
    def subscription_plan(self):
        """Gets the subscription_plan of this SubscriptionStartBody.  # noqa: E501

        The ID for the subscription plan to be used (Can also be the code name)  # noqa: E501

        :return: The subscription_plan of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._subscription_plan

    @subscription_plan.setter
    def subscription_plan(self, subscription_plan):
        """Sets the subscription_plan of this SubscriptionStartBody.

        The ID for the subscription plan to be used (Can also be the code name)  # noqa: E501

        :param subscription_plan: The subscription_plan of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """
        if subscription_plan is None:
            raise ValueError("Invalid value for `subscription_plan`, must not be `None`")  # noqa: E501

        self._subscription_plan = subscription_plan

    @property
    def payment_details(self):
        """Gets the payment_details of this SubscriptionStartBody.  # noqa: E501

        The Id for the customer's payment details to be used  # noqa: E501

        :return: The payment_details of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._payment_details

    @payment_details.setter
    def payment_details(self, payment_details):
        """Sets the payment_details of this SubscriptionStartBody.

        The Id for the customer's payment details to be used  # noqa: E501

        :param payment_details: The payment_details of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """

        self._payment_details = payment_details

    @property
    def card_token(self):
        """Gets the card_token of this SubscriptionStartBody.  # noqa: E501

        A stripe card token that's been created using Stripe's js sdk. It'll create the payment details for the customer.  # noqa: E501

        :return: The card_token of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._card_token

    @card_token.setter
    def card_token(self, card_token):
        """Sets the card_token of this SubscriptionStartBody.

        A stripe card token that's been created using Stripe's js sdk. It'll create the payment details for the customer.  # noqa: E501

        :param card_token: The card_token of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """

        self._card_token = card_token

    @property
    def price(self):
        """Gets the price of this SubscriptionStartBody.  # noqa: E501

        The ID for the price to be used  # noqa: E501

        :return: The price of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this SubscriptionStartBody.

        The ID for the price to be used  # noqa: E501

        :param price: The price of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def schedule(self):
        """Gets the schedule of this SubscriptionStartBody.  # noqa: E501

        The schedule of the plan that is to be started. Only used if price isn't given. Requires currency as well.  # noqa: E501

        :return: The schedule of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this SubscriptionStartBody.

        The schedule of the plan that is to be started. Only used if price isn't given. Requires currency as well.  # noqa: E501

        :param schedule: The schedule of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """
        allowed_values = ["week", "month", "year", "one-off"]  # noqa: E501
        if schedule not in allowed_values:
            raise ValueError(
                "Invalid value for `schedule` ({0}), must be one of {1}"  # noqa: E501
                .format(schedule, allowed_values)
            )

        self._schedule = schedule

    @property
    def currency(self):
        """Gets the currency of this SubscriptionStartBody.  # noqa: E501

        The currency of the plan that is to be started. Only used if price isn't given. Requires schedule as well.  # noqa: E501

        :return: The currency of this SubscriptionStartBody.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this SubscriptionStartBody.

        The currency of the plan that is to be started. Only used if price isn't given. Requires schedule as well.  # noqa: E501

        :param currency: The currency of this SubscriptionStartBody.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def seat_numbrers(self):
        """Gets the seat_numbrers of this SubscriptionStartBody.  # noqa: E501


        :return: The seat_numbrers of this SubscriptionStartBody.  # noqa: E501
        :rtype: int
        """
        return self._seat_numbrers

    @seat_numbrers.setter
    def seat_numbrers(self, seat_numbrers):
        """Sets the seat_numbrers of this SubscriptionStartBody.


        :param seat_numbrers: The seat_numbrers of this SubscriptionStartBody.  # noqa: E501
        :type: int
        """

        self._seat_numbrers = seat_numbrers

    @property
    def deny_trial(self):
        """Gets the deny_trial of this SubscriptionStartBody.  # noqa: E501


        :return: The deny_trial of this SubscriptionStartBody.  # noqa: E501
        :rtype: Bool
        """
        return self._deny_trial

    @deny_trial.setter
    def deny_trial(self, deny_trial):
        """Sets the deny_trial of this SubscriptionStartBody.


        :param deny_trial: The deny_trial of this SubscriptionStartBody.  # noqa: E501
        :type: Bool
        """

        self._deny_trial = deny_trial

    @property
    def metadata(self):
        """Gets the metadata of this SubscriptionStartBody.  # noqa: E501

        Any metadata you want to add to a subscription  # noqa: E501

        :return: The metadata of this SubscriptionStartBody.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this SubscriptionStartBody.

        Any metadata you want to add to a subscription  # noqa: E501

        :param metadata: The metadata of this SubscriptionStartBody.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionStartBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionStartBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
