# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckoutSubscriptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan': 'str',
        'price': 'str',
        'seat_number': 'int'
    }

    attribute_map = {
        'plan': 'plan',
        'price': 'price',
        'seat_number': 'seat_number'
    }

    def __init__(self, plan=None, price=None, seat_number=None):  # noqa: E501
        """CheckoutSubscriptions - a model defined in Swagger"""  # noqa: E501
        self._plan = None
        self._price = None
        self._seat_number = None
        self.discriminator = None
        if plan is not None:
            self.plan = plan
        if price is not None:
            self.price = price
        if seat_number is not None:
            self.seat_number = seat_number

    @property
    def plan(self):
        """Gets the plan of this CheckoutSubscriptions.  # noqa: E501


        :return: The plan of this CheckoutSubscriptions.  # noqa: E501
        :rtype: str
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this CheckoutSubscriptions.


        :param plan: The plan of this CheckoutSubscriptions.  # noqa: E501
        :type: str
        """

        self._plan = plan

    @property
    def price(self):
        """Gets the price of this CheckoutSubscriptions.  # noqa: E501


        :return: The price of this CheckoutSubscriptions.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this CheckoutSubscriptions.


        :param price: The price of this CheckoutSubscriptions.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def seat_number(self):
        """Gets the seat_number of this CheckoutSubscriptions.  # noqa: E501


        :return: The seat_number of this CheckoutSubscriptions.  # noqa: E501
        :rtype: int
        """
        return self._seat_number

    @seat_number.setter
    def seat_number(self, seat_number):
        """Sets the seat_number of this CheckoutSubscriptions.


        :param seat_number: The seat_number of this CheckoutSubscriptions.  # noqa: E501
        :type: int
        """

        self._seat_number = seat_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckoutSubscriptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckoutSubscriptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
