# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckoutItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'amount': 'int',
        'currency': 'str',
        'include_tax': 'bool',
        'tax_type': 'str'
    }

    attribute_map = {
        'description': 'description',
        'amount': 'amount',
        'currency': 'currency',
        'include_tax': 'include_tax',
        'tax_type': 'tax_type'
    }

    def __init__(self, description=None, amount=None, currency=None, include_tax=None, tax_type=None):  # noqa: E501
        """CheckoutItems - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._amount = None
        self._currency = None
        self._include_tax = None
        self._tax_type = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if amount is not None:
            self.amount = amount
        if currency is not None:
            self.currency = currency
        if include_tax is not None:
            self.include_tax = include_tax
        if tax_type is not None:
            self.tax_type = tax_type

    @property
    def description(self):
        """Gets the description of this CheckoutItems.  # noqa: E501


        :return: The description of this CheckoutItems.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CheckoutItems.


        :param description: The description of this CheckoutItems.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def amount(self):
        """Gets the amount of this CheckoutItems.  # noqa: E501


        :return: The amount of this CheckoutItems.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this CheckoutItems.


        :param amount: The amount of this CheckoutItems.  # noqa: E501
        :type: int
        """

        self._amount = amount

    @property
    def currency(self):
        """Gets the currency of this CheckoutItems.  # noqa: E501


        :return: The currency of this CheckoutItems.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this CheckoutItems.


        :param currency: The currency of this CheckoutItems.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def include_tax(self):
        """Gets the include_tax of this CheckoutItems.  # noqa: E501


        :return: The include_tax of this CheckoutItems.  # noqa: E501
        :rtype: bool
        """
        return self._include_tax

    @include_tax.setter
    def include_tax(self, include_tax):
        """Sets the include_tax of this CheckoutItems.


        :param include_tax: The include_tax of this CheckoutItems.  # noqa: E501
        :type: bool
        """

        self._include_tax = include_tax

    @property
    def tax_type(self):
        """Gets the tax_type of this CheckoutItems.  # noqa: E501


        :return: The tax_type of this CheckoutItems.  # noqa: E501
        :rtype: str
        """
        return self._tax_type

    @tax_type.setter
    def tax_type(self, tax_type):
        """Sets the tax_type of this CheckoutItems.


        :param tax_type: The tax_type of this CheckoutItems.  # noqa: E501
        :type: str
        """

        self._tax_type = tax_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckoutItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckoutItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
