# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2002(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'limits': 'list[Limit]',
        'features': 'list[Feature]',
        'user_count': 'int'
    }

    attribute_map = {
        'limits': 'limits',
        'features': 'features',
        'user_count': 'user_count'
    }

    def __init__(self, limits=None, features=None, user_count=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger"""  # noqa: E501
        self._limits = None
        self._features = None
        self._user_count = None
        self.discriminator = None
        if limits is not None:
            self.limits = limits
        if features is not None:
            self.features = features
        if user_count is not None:
            self.user_count = user_count

    @property
    def limits(self):
        """Gets the limits of this InlineResponse2002.  # noqa: E501


        :return: The limits of this InlineResponse2002.  # noqa: E501
        :rtype: list[Limit]
        """
        return self._limits

    @limits.setter
    def limits(self, limits):
        """Sets the limits of this InlineResponse2002.


        :param limits: The limits of this InlineResponse2002.  # noqa: E501
        :type: list[Limit]
        """

        self._limits = limits

    @property
    def features(self):
        """Gets the features of this InlineResponse2002.  # noqa: E501


        :return: The features of this InlineResponse2002.  # noqa: E501
        :rtype: list[Feature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this InlineResponse2002.


        :param features: The features of this InlineResponse2002.  # noqa: E501
        :type: list[Feature]
        """

        self._features = features

    @property
    def user_count(self):
        """Gets the user_count of this InlineResponse2002.  # noqa: E501


        :return: The user_count of this InlineResponse2002.  # noqa: E501
        :rtype: int
        """
        return self._user_count

    @user_count.setter
    def user_count(self, user_count):
        """Sets the user_count of this InlineResponse2002.


        :param user_count: The user_count of this InlineResponse2002.  # noqa: E501
        :type: int
        """

        self._user_count = user_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
