# coding: utf-8

"""
    BillaBear

    The REST API provided by BillaBear  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@billabear.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Metric(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'code': 'str',
        'aggregation_method': 'str',
        'aggregation_property': 'str',
        'filters': 'list[MetricFilter]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'code': 'code',
        'aggregation_method': 'aggregation_method',
        'aggregation_property': 'aggregation_property',
        'filters': 'filters'
    }

    def __init__(self, id=None, name=None, code=None, aggregation_method=None, aggregation_property=None, filters=None):  # noqa: E501
        """Metric - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._code = None
        self._aggregation_method = None
        self._aggregation_property = None
        self._filters = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if code is not None:
            self.code = code
        if aggregation_method is not None:
            self.aggregation_method = aggregation_method
        if aggregation_property is not None:
            self.aggregation_property = aggregation_property
        if filters is not None:
            self.filters = filters

    @property
    def id(self):
        """Gets the id of this Metric.  # noqa: E501


        :return: The id of this Metric.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Metric.


        :param id: The id of this Metric.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Metric.  # noqa: E501


        :return: The name of this Metric.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Metric.


        :param name: The name of this Metric.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def code(self):
        """Gets the code of this Metric.  # noqa: E501


        :return: The code of this Metric.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Metric.


        :param code: The code of this Metric.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def aggregation_method(self):
        """Gets the aggregation_method of this Metric.  # noqa: E501


        :return: The aggregation_method of this Metric.  # noqa: E501
        :rtype: str
        """
        return self._aggregation_method

    @aggregation_method.setter
    def aggregation_method(self, aggregation_method):
        """Sets the aggregation_method of this Metric.


        :param aggregation_method: The aggregation_method of this Metric.  # noqa: E501
        :type: str
        """
        allowed_values = ["count", "sum", "latest", "unique_count", "max"]  # noqa: E501
        if aggregation_method not in allowed_values:
            raise ValueError(
                "Invalid value for `aggregation_method` ({0}), must be one of {1}"  # noqa: E501
                .format(aggregation_method, allowed_values)
            )

        self._aggregation_method = aggregation_method

    @property
    def aggregation_property(self):
        """Gets the aggregation_property of this Metric.  # noqa: E501


        :return: The aggregation_property of this Metric.  # noqa: E501
        :rtype: str
        """
        return self._aggregation_property

    @aggregation_property.setter
    def aggregation_property(self, aggregation_property):
        """Sets the aggregation_property of this Metric.


        :param aggregation_property: The aggregation_property of this Metric.  # noqa: E501
        :type: str
        """

        self._aggregation_property = aggregation_property

    @property
    def filters(self):
        """Gets the filters of this Metric.  # noqa: E501


        :return: The filters of this Metric.  # noqa: E501
        :rtype: list[MetricFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this Metric.


        :param filters: The filters of this Metric.  # noqa: E501
        :type: list[MetricFilter]
        """

        self._filters = filters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Metric, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Metric):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
